//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarMap2D.Controls.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarMap2D.Controls.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] compass {
            get {
                object obj = ResourceManager.GetObject("compass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the simple tab-delimited localization file.
        ///As you can see only the &quot;[]&quot; tags and tab delimited key-value pairs matter for the localization.
        ///The tab-delimited text can also include comments, etc. by adding a new tab-delimited field.
        ///
        ///[en-US]
        ///textHydra	Hydra
        ///textAquarius	Aquarius
        ///textOphiuchus	Ophiuchus
        ///textLeo	Leo
        ///textBoötes	Boötes
        ///textPisces	Pisces
        ///textSagittarius	Sagittarius
        ///textCygnus	Cygnus
        ///textTaurus	Taurus
        ///textCamelopardalis	Camelopardalis
        ///textAndromeda	Andromeda
        ///textVirgo	Virg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Constellations {
            get {
                return ResourceManager.GetString("Constellations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbols images for files:
        ///* minor_planet_eris1.svg
        ///* minor_planet_eris2.svg
        ///* minor_planet_gonggong.svg
        ///* minor_planet_haumea.svg
        ///* minor_planet_makemake.svg
        ///* minor_planet_orcus.svg
        ///* minor_planet_quoar.svg
        ///are copyright by Wikipedia, CC BY-SA 4.0, https://creativecommons.org/licenses/by-sa/4.0/
        ///
        ///MIT-licensed files, Copyright(c) 2022 Petteri Kautonen:
        ///* dwarf_pluto.svg
        ///* earth.svg
        ///* jupiter.png
        ///* mars.png
        ///* mercury.png
        ///* minor_planet_ceres.svg
        ///* minor_planet_chiron.svg
        ///* minor_planet_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] earth {
            get {
                object obj = ResourceManager.GetObject("earth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ic_fluent_arrow_right_48_filled {
            get {
                object obj = ResourceManager.GetObject("ic_fluent_arrow_right_48_filled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ic_fluent_arrow_undo_48_filled {
            get {
                object obj = ResourceManager.GetObject("ic_fluent_arrow_undo_48_filled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ic_fluent_checkbox_checked_24_filled {
            get {
                object obj = ResourceManager.GetObject("ic_fluent_checkbox_checked_24_filled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ic_fluent_checkbox_unchecked_24_filled {
            get {
                object obj = ResourceManager.GetObject("ic_fluent_checkbox_unchecked_24_filled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ic_fluent_pause_48_filled {
            get {
                object obj = ResourceManager.GetObject("ic_fluent_pause_48_filled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ic_fluent_play_48_filled {
            get {
                object obj = ResourceManager.GetObject("ic_fluent_play_48_filled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ic_fluent_play_circle_48_filled {
            get {
                object obj = ResourceManager.GetObject("ic_fluent_play_circle_48_filled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] minor_planet_ceres {
            get {
                object obj = ResourceManager.GetObject("minor_planet_ceres", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] minor_planet_chiron {
            get {
                object obj = ResourceManager.GetObject("minor_planet_chiron", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] minor_planet_eris1 {
            get {
                object obj = ResourceManager.GetObject("minor_planet_eris1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] minor_planet_eris2 {
            get {
                object obj = ResourceManager.GetObject("minor_planet_eris2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] minor_planet_gonggong {
            get {
                object obj = ResourceManager.GetObject("minor_planet_gonggong", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] minor_planet_haumea {
            get {
                object obj = ResourceManager.GetObject("minor_planet_haumea", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] minor_planet_juno {
            get {
                object obj = ResourceManager.GetObject("minor_planet_juno", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] minor_planet_makemake {
            get {
                object obj = ResourceManager.GetObject("minor_planet_makemake", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] minor_planet_orcus {
            get {
                object obj = ResourceManager.GetObject("minor_planet_orcus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] minor_planet_pallas {
            get {
                object obj = ResourceManager.GetObject("minor_planet_pallas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] minor_planet_pluto {
            get {
                object obj = ResourceManager.GetObject("minor_planet_pluto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] minor_planet_quoar {
            get {
                object obj = ResourceManager.GetObject("minor_planet_quoar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] minor_planet_sedna {
            get {
                object obj = ResourceManager.GetObject("minor_planet_sedna", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] minor_planet_vesta {
            get {
                object obj = ResourceManager.GetObject("minor_planet_vesta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] moon {
            get {
                object obj = ResourceManager.GetObject("moon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] planet_jupiter {
            get {
                object obj = ResourceManager.GetObject("planet_jupiter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] planet_mars {
            get {
                object obj = ResourceManager.GetObject("planet_mars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] planet_mercury {
            get {
                object obj = ResourceManager.GetObject("planet_mercury", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] planet_neptune {
            get {
                object obj = ResourceManager.GetObject("planet_neptune", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] planet_saturn {
            get {
                object obj = ResourceManager.GetObject("planet_saturn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] planet_uranus {
            get {
                object obj = ResourceManager.GetObject("planet_uranus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] planet_venus {
            get {
                object obj = ResourceManager.GetObject("planet_venus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sun {
            get {
                object obj = ResourceManager.GetObject("sun", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
