//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace StarMap2D.Common.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("StarMap2D.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the simple tab-delimited localization file.
        ///As you can see only the &quot;[]&quot; tags and tab delimited key-value pairs matter for the localization.
        ///The tab-delimited text can also include comments, etc. by adding a new tab-delimited field.
        ///
        ///[en-US]
        ///textHydra	Hydra
        ///textAquarius	Aquarius
        ///textOphiuchus	Ophiuchus
        ///textLeo	Leo
        ///textBo�tes	Bo�tes
        ///textPisces	Pisces
        ///textSagittarius	Sagittarius
        ///textCygnus	Cygnus
        ///textTaurus	Taurus
        ///textCamelopardalis	Camelopardalis
        ///textAndromeda	Andromeda
        ///textVirgo	Virg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Constellations {
            get {
                return ResourceManager.GetString("Constellations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the simple tab-delimited localization file.
        ///As you can see only the &quot;[]&quot; tags and tab delimited key-value pairs matter for the localization.
        ///The tab-delimited text can also include comments, etc. by adding a new tab-delimited field.
        ///
        ///[en-US]
        ///textSun	Sun
        ///textMercury	Mercury
        ///textVenus	Venus
        ///textEarth	Earth
        ///textMars	Mars
        ///textJupiter	Jupiter
        ///textSaturn	Saturn
        ///textUranus	Uranus
        ///textNeptune	Neptune
        ///textPluto	Pluto
        ///textCeres	Ceres
        ///textOrcus	Orcus
        ///textPluto	Pluto
        ///textHaumea	Haumea
        ///textQua [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SolarSystemObjects {
            get {
                return ResourceManager.GetString("SolarSystemObjects", resourceCulture);
            }
        }
    }
}
