//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarMap2D.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CelestialObjects {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CelestialObjects() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarMap2D.Localization.CelestialObjects", typeof(CelestialObjects).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceres.
        /// </summary>
        public static string Ceres {
            get {
                return ResourceManager.GetString("Ceres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        public static string Earth {
            get {
                return ResourceManager.GetString("Earth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eris.
        /// </summary>
        public static string Eris {
            get {
                return ResourceManager.GetString("Eris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haumea.
        /// </summary>
        public static string Haumea {
            get {
                return ResourceManager.GetString("Haumea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jupiter.
        /// </summary>
        public static string Jupiter {
            get {
                return ResourceManager.GetString("Jupiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makemake.
        /// </summary>
        public static string Makemake {
            get {
                return ResourceManager.GetString("Makemake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mars.
        /// </summary>
        public static string Mars {
            get {
                return ResourceManager.GetString("Mars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercury.
        /// </summary>
        public static string Mercury {
            get {
                return ResourceManager.GetString("Mercury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon.
        /// </summary>
        public static string Moon {
            get {
                return ResourceManager.GetString("Moon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neptune.
        /// </summary>
        public static string Neptune {
            get {
                return ResourceManager.GetString("Neptune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pluto.
        /// </summary>
        public static string Pluto {
            get {
                return ResourceManager.GetString("Pluto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturn.
        /// </summary>
        public static string Saturn {
            get {
                return ResourceManager.GetString("Saturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uranus.
        /// </summary>
        public static string Uranus {
            get {
                return ResourceManager.GetString("Uranus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venus.
        /// </summary>
        public static string Venus {
            get {
                return ResourceManager.GetString("Venus", resourceCulture);
            }
        }
    }
}
