//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarMap2D.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constellations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constellations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarMap2D.Localization.Constellations", typeof(Constellations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andromeda.
        /// </summary>
        public static string Andromeda {
            get {
                return ResourceManager.GetString("Andromeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antlia.
        /// </summary>
        public static string Antlia {
            get {
                return ResourceManager.GetString("Antlia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apus.
        /// </summary>
        public static string Apus {
            get {
                return ResourceManager.GetString("Apus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquarius.
        /// </summary>
        public static string Aquarius {
            get {
                return ResourceManager.GetString("Aquarius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquila.
        /// </summary>
        public static string Aquila {
            get {
                return ResourceManager.GetString("Aquila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        public static string Ara {
            get {
                return ResourceManager.GetString("Ara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aries.
        /// </summary>
        public static string Aries {
            get {
                return ResourceManager.GetString("Aries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auriga.
        /// </summary>
        public static string Auriga {
            get {
                return ResourceManager.GetString("Auriga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boötes.
        /// </summary>
        public static string Boötes {
            get {
                return ResourceManager.GetString("Boötes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caelum.
        /// </summary>
        public static string Caelum {
            get {
                return ResourceManager.GetString("Caelum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camelopardalis.
        /// </summary>
        public static string Camelopardalis {
            get {
                return ResourceManager.GetString("Camelopardalis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancer.
        /// </summary>
        public static string Cancer {
            get {
                return ResourceManager.GetString("Cancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canes Venatici.
        /// </summary>
        public static string CanesVenatici {
            get {
                return ResourceManager.GetString("CanesVenatici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canis Major.
        /// </summary>
        public static string CanisMajor {
            get {
                return ResourceManager.GetString("CanisMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canis Minor.
        /// </summary>
        public static string CanisMinor {
            get {
                return ResourceManager.GetString("CanisMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capricornus.
        /// </summary>
        public static string Capricornus {
            get {
                return ResourceManager.GetString("Capricornus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carina.
        /// </summary>
        public static string Carina {
            get {
                return ResourceManager.GetString("Carina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cassiopeia.
        /// </summary>
        public static string Cassiopeia {
            get {
                return ResourceManager.GetString("Cassiopeia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centaurus.
        /// </summary>
        public static string Centaurus {
            get {
                return ResourceManager.GetString("Centaurus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cepheus.
        /// </summary>
        public static string Cepheus {
            get {
                return ResourceManager.GetString("Cepheus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cetus.
        /// </summary>
        public static string Cetus {
            get {
                return ResourceManager.GetString("Cetus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chamaeleon.
        /// </summary>
        public static string Chamaeleon {
            get {
                return ResourceManager.GetString("Chamaeleon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circinus.
        /// </summary>
        public static string Circinus {
            get {
                return ResourceManager.GetString("Circinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columba.
        /// </summary>
        public static string Columba {
            get {
                return ResourceManager.GetString("Columba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coma Berenices.
        /// </summary>
        public static string ComaBerenices {
            get {
                return ResourceManager.GetString("ComaBerenices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corona Australis.
        /// </summary>
        public static string CoronaAustralis {
            get {
                return ResourceManager.GetString("CoronaAustralis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corona Borealis.
        /// </summary>
        public static string CoronaBorealis {
            get {
                return ResourceManager.GetString("CoronaBorealis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corvus.
        /// </summary>
        public static string Corvus {
            get {
                return ResourceManager.GetString("Corvus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crater.
        /// </summary>
        public static string Crater {
            get {
                return ResourceManager.GetString("Crater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crux.
        /// </summary>
        public static string Crux {
            get {
                return ResourceManager.GetString("Crux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cygnus.
        /// </summary>
        public static string Cygnus {
            get {
                return ResourceManager.GetString("Cygnus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delphinus.
        /// </summary>
        public static string Delphinus {
            get {
                return ResourceManager.GetString("Delphinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dorado.
        /// </summary>
        public static string Dorado {
            get {
                return ResourceManager.GetString("Dorado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draco.
        /// </summary>
        public static string Draco {
            get {
                return ResourceManager.GetString("Draco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equuleus.
        /// </summary>
        public static string Equuleus {
            get {
                return ResourceManager.GetString("Equuleus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eridanus.
        /// </summary>
        public static string Eridanus {
            get {
                return ResourceManager.GetString("Eridanus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornax.
        /// </summary>
        public static string Fornax {
            get {
                return ResourceManager.GetString("Fornax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemini.
        /// </summary>
        public static string Gemini {
            get {
                return ResourceManager.GetString("Gemini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grus.
        /// </summary>
        public static string Grus {
            get {
                return ResourceManager.GetString("Grus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hercules.
        /// </summary>
        public static string Hercules {
            get {
                return ResourceManager.GetString("Hercules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horologium.
        /// </summary>
        public static string Horologium {
            get {
                return ResourceManager.GetString("Horologium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydra.
        /// </summary>
        public static string Hydra {
            get {
                return ResourceManager.GetString("Hydra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrus.
        /// </summary>
        public static string Hydrus {
            get {
                return ResourceManager.GetString("Hydrus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indus.
        /// </summary>
        public static string Indus {
            get {
                return ResourceManager.GetString("Indus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lacerta.
        /// </summary>
        public static string Lacerta {
            get {
                return ResourceManager.GetString("Lacerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leo.
        /// </summary>
        public static string Leo {
            get {
                return ResourceManager.GetString("Leo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leo Minor.
        /// </summary>
        public static string LeoMinor {
            get {
                return ResourceManager.GetString("LeoMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lepus.
        /// </summary>
        public static string Lepus {
            get {
                return ResourceManager.GetString("Lepus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libra.
        /// </summary>
        public static string Libra {
            get {
                return ResourceManager.GetString("Libra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lupus.
        /// </summary>
        public static string Lupus {
            get {
                return ResourceManager.GetString("Lupus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lynx.
        /// </summary>
        public static string Lynx {
            get {
                return ResourceManager.GetString("Lynx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyra.
        /// </summary>
        public static string Lyra {
            get {
                return ResourceManager.GetString("Lyra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensa.
        /// </summary>
        public static string Mensa {
            get {
                return ResourceManager.GetString("Mensa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microscopium.
        /// </summary>
        public static string Microscopium {
            get {
                return ResourceManager.GetString("Microscopium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monoceros.
        /// </summary>
        public static string Monoceros {
            get {
                return ResourceManager.GetString("Monoceros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musca.
        /// </summary>
        public static string Musca {
            get {
                return ResourceManager.GetString("Musca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norma.
        /// </summary>
        public static string Norma {
            get {
                return ResourceManager.GetString("Norma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octans.
        /// </summary>
        public static string Octans {
            get {
                return ResourceManager.GetString("Octans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ophiuchus.
        /// </summary>
        public static string Ophiuchus {
            get {
                return ResourceManager.GetString("Ophiuchus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orion.
        /// </summary>
        public static string Orion {
            get {
                return ResourceManager.GetString("Orion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pavo.
        /// </summary>
        public static string Pavo {
            get {
                return ResourceManager.GetString("Pavo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pegasus.
        /// </summary>
        public static string Pegasus {
            get {
                return ResourceManager.GetString("Pegasus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perseus.
        /// </summary>
        public static string Perseus {
            get {
                return ResourceManager.GetString("Perseus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phoenix.
        /// </summary>
        public static string Phoenix {
            get {
                return ResourceManager.GetString("Phoenix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictor.
        /// </summary>
        public static string Pictor {
            get {
                return ResourceManager.GetString("Pictor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pisces.
        /// </summary>
        public static string Pisces {
            get {
                return ResourceManager.GetString("Pisces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piscis Austrinus.
        /// </summary>
        public static string PiscisAustrinus {
            get {
                return ResourceManager.GetString("PiscisAustrinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puppis.
        /// </summary>
        public static string Puppis {
            get {
                return ResourceManager.GetString("Puppis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyxis.
        /// </summary>
        public static string Pyxis {
            get {
                return ResourceManager.GetString("Pyxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reticulum.
        /// </summary>
        public static string Reticulum {
            get {
                return ResourceManager.GetString("Reticulum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagitta.
        /// </summary>
        public static string Sagitta {
            get {
                return ResourceManager.GetString("Sagitta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagittarius.
        /// </summary>
        public static string Sagittarius {
            get {
                return ResourceManager.GetString("Sagittarius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorpius.
        /// </summary>
        public static string Scorpius {
            get {
                return ResourceManager.GetString("Scorpius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sculptor.
        /// </summary>
        public static string Sculptor {
            get {
                return ResourceManager.GetString("Sculptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scutum.
        /// </summary>
        public static string Scutum {
            get {
                return ResourceManager.GetString("Scutum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serpens Caput.
        /// </summary>
        public static string SerpensCaput {
            get {
                return ResourceManager.GetString("SerpensCaput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serpens Cauda.
        /// </summary>
        public static string SerpensCauda {
            get {
                return ResourceManager.GetString("SerpensCauda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sextans.
        /// </summary>
        public static string Sextans {
            get {
                return ResourceManager.GetString("Sextans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taurus.
        /// </summary>
        public static string Taurus {
            get {
                return ResourceManager.GetString("Taurus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telescopium.
        /// </summary>
        public static string Telescopium {
            get {
                return ResourceManager.GetString("Telescopium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangulum.
        /// </summary>
        public static string Triangulum {
            get {
                return ResourceManager.GetString("Triangulum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangulum Australe.
        /// </summary>
        public static string TriangulumAustrale {
            get {
                return ResourceManager.GetString("TriangulumAustrale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tucana.
        /// </summary>
        public static string Tucana {
            get {
                return ResourceManager.GetString("Tucana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ursa Major.
        /// </summary>
        public static string UrsaMajor {
            get {
                return ResourceManager.GetString("UrsaMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ursa Minor.
        /// </summary>
        public static string UrsaMinor {
            get {
                return ResourceManager.GetString("UrsaMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vela.
        /// </summary>
        public static string Vela {
            get {
                return ResourceManager.GetString("Vela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virgo.
        /// </summary>
        public static string Virgo {
            get {
                return ResourceManager.GetString("Virgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volans.
        /// </summary>
        public static string Volans {
            get {
                return ResourceManager.GetString("Volans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulpecula.
        /// </summary>
        public static string Vulpecula {
            get {
                return ResourceManager.GetString("Vulpecula", resourceCulture);
            }
        }
    }
}
