//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarMap2D.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MoonData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MoonData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarMap2D.Localization.MoonData", typeof(MoonData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First quarter.
        /// </summary>
        public static string MoonFirstQuarter {
            get {
                return ResourceManager.GetString("MoonFirstQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full moon.
        /// </summary>
        public static string MoonFullMoon {
            get {
                return ResourceManager.GetString("MoonFullMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon illuminated (%).
        /// </summary>
        public static string MoonIlluminated {
            get {
                return ResourceManager.GetString("MoonIlluminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last quarter.
        /// </summary>
        public static string MoonLastQuarter {
            get {
                return ResourceManager.GetString("MoonLastQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New moon.
        /// </summary>
        public static string MoonNewMoon {
            get {
                return ResourceManager.GetString("MoonNewMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon phase number.
        /// </summary>
        public static string MoonPhaseNumber {
            get {
                return ResourceManager.GetString("MoonPhaseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waning crescent.
        /// </summary>
        public static string MoonWaningCrescent {
            get {
                return ResourceManager.GetString("MoonWaningCrescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waning gibbous.
        /// </summary>
        public static string MoonWaningGibbous {
            get {
                return ResourceManager.GetString("MoonWaningGibbous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waxing crescent.
        /// </summary>
        public static string MoonWaxingCrescent {
            get {
                return ResourceManager.GetString("MoonWaxingCrescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waxing gibbous.
        /// </summary>
        public static string MoonWaxingGibbous {
            get {
                return ResourceManager.GetString("MoonWaxingGibbous", resourceCulture);
            }
        }
    }
}
