//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarMap2D.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarMap2D.Localization.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross hair size.
        /// </summary>
        public static string CrossHairSize {
            get {
                return ResourceManager.GetString("CrossHairSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw constellation boundaries.
        /// </summary>
        public static string DrawConstellationBoundaries {
            get {
                return ResourceManager.GetString("DrawConstellationBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw constellation labels.
        /// </summary>
        public static string DrawConstellationNames {
            get {
                return ResourceManager.GetString("DrawConstellationNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw constellations.
        /// </summary>
        public static string DrawConstellations {
            get {
                return ResourceManager.GetString("DrawConstellations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw cross hair.
        /// </summary>
        public static string DrawCrossHair {
            get {
                return ResourceManager.GetString("DrawCrossHair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded ({0}).
        /// </summary>
        public static string EmbeddedParameter {
            get {
                return ResourceManager.GetString("EmbeddedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert east-west axis of the map.
        /// </summary>
        public static string InvertEastWestAxis {
            get {
                return ResourceManager.GetString("InvertEastWestAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location name.
        /// </summary>
        public static string LocationName {
            get {
                return ResourceManager.GetString("LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select location.
        /// </summary>
        public static string SelectLocation {
            get {
                return ResourceManager.GetString("SelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star catalog to use.
        /// </summary>
        public static string StarCatalogSelection {
            get {
                return ResourceManager.GetString("StarCatalogSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StarMap2D.
        /// </summary>
        public static string StarMap2D {
            get {
                return ResourceManager.GetString("StarMap2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language (localization, a restart is required).
        /// </summary>
        public static string UiLanguageRequireRestart {
            get {
                return ResourceManager.GetString("UiLanguageRequireRestart", resourceCulture);
            }
        }
    }
}
