//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace StarMap2D.Localization {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class UI {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("StarMap2D.Localization.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above horizon.
        /// </summary>
        public static string AboveHorizon {
            get {
                return ResourceManager.GetString("AboveHorizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapt.
        /// </summary>
        public static string Adapt {
            get {
                return ResourceManager.GetString("Adapt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional data.
        /// </summary>
        public static string AdditionalData {
            get {
                return ResourceManager.GetString("AdditionalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always re-scale.
        /// </summary>
        public static string AlwaysReScale {
            get {
                return ResourceManager.GetString("AlwaysReScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azimuth.
        /// </summary>
        public static string Azimuth {
            get {
                return ResourceManager.GetString("Azimuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celestial object.
        /// </summary>
        public static string CelestialObject {
            get {
                return ResourceManager.GetString("CelestialObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celestial object details.
        /// </summary>
        public static string CelestialObjectDetails {
            get {
                return ResourceManager.GetString("CelestialObjectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celestial objects.
        /// </summary>
        public static string CelestialObjects {
            get {
                return ResourceManager.GetString("CelestialObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass direction.
        /// </summary>
        public static string CompassDirection {
            get {
                return ResourceManager.GetString("CompassDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constellation border line color.
        /// </summary>
        public static string ConstellationBorderLineColor {
            get {
                return ResourceManager.GetString("ConstellationBorderLineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constellation line color.
        /// </summary>
        public static string ConstellationLineColor {
            get {
                return ResourceManager.GetString("ConstellationLineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates.
        /// </summary>
        public static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross hair size.
        /// </summary>
        public static string CrossHairSize {
            get {
                return ResourceManager.GetString("CrossHairSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV files.
        /// </summary>
        public static string CSVFiles {
            get {
                return ResourceManager.GetString("CSVFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current day.
        /// </summary>
        public static string CurrentDay {
            get {
                return ResourceManager.GetString("CurrentDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data formatting culture (i.e. numbers, etc).
        /// </summary>
        public static string DataFormattingCulture {
            get {
                return ResourceManager.GetString("DataFormattingCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data URL.
        /// </summary>
        public static string DataURL {
            get {
                return ResourceManager.GetString("DataURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and number formatting.
        /// </summary>
        public static string DateAndNumberFormattingSettings {
            get {
                return ResourceManager.GetString("DateAndNumberFormattingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        public static string DateAndTime {
            get {
                return ResourceManager.GetString("DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time formatting culture.
        /// </summary>
        public static string DateAndTimeFormattingCulture {
            get {
                return ResourceManager.GetString("DateAndTimeFormattingCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declination.
        /// </summary>
        public static string Declination {
            get {
                return ResourceManager.GetString("Declination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declination (degrees).
        /// </summary>
        public static string DeclinationDegrees {
            get {
                return ResourceManager.GetString("DeclinationDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use the object.
        /// </summary>
        public static string DoNotUseTheObject {
            get {
                return ResourceManager.GetString("DoNotUseTheObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw constellation borders.
        /// </summary>
        public static string DrawConstellationBorders {
            get {
                return ResourceManager.GetString("DrawConstellationBorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw constellation boundaries.
        /// </summary>
        public static string DrawConstellationBoundaries {
            get {
                return ResourceManager.GetString("DrawConstellationBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw constellation labels.
        /// </summary>
        public static string DrawConstellationNames {
            get {
                return ResourceManager.GetString("DrawConstellationNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw constellations.
        /// </summary>
        public static string DrawConstellations {
            get {
                return ResourceManager.GetString("DrawConstellations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw cross hair.
        /// </summary>
        public static string DrawCrossHair {
            get {
                return ResourceManager.GetString("DrawCrossHair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded ({0}).
        /// </summary>
        public static string EmbeddedParameter {
            get {
                return ResourceManager.GetString("EmbeddedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CSV.
        /// </summary>
        public static string ExportCSV {
            get {
                return ResourceManager.GetString("ExportCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font (monospaced).
        /// </summary>
        public static string FontMonospaced {
            get {
                return ResourceManager.GetString("FontMonospaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts and appearance.
        /// </summary>
        public static string FontsAndAppearance {
            get {
                return ResourceManager.GetString("FontsAndAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal, altitude (degrees).
        /// </summary>
        public static string HorizontalAltitudeDegrees {
            get {
                return ResourceManager.GetString("HorizontalAltitudeDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal coordinates in degrees.
        /// </summary>
        public static string HorizontalCoordinatesInDegrees {
            get {
                return ResourceManager.GetString("HorizontalCoordinatesInDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour - 1.
        /// </summary>
        public static string HourMinusOne {
            get {
                return ResourceManager.GetString("HourMinusOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour + 1.
        /// </summary>
        public static string HourPlusOne {
            get {
                return ResourceManager.GetString("HourPlusOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert east-west.
        /// </summary>
        public static string InvertEastWest {
            get {
                return ResourceManager.GetString("InvertEastWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert east-west axis of the map.
        /// </summary>
        public static string InvertEastWestAxis {
            get {
                return ResourceManager.GetString("InvertEastWestAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to location.
        /// </summary>
        public static string JumpToLcation {
            get {
                return ResourceManager.GetString("JumpToLcation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known object symbols.
        /// </summary>
        public static string KnownObjectSymbols {
            get {
                return ResourceManager.GetString("KnownObjectSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location name.
        /// </summary>
        public static string LocationName {
            get {
                return ResourceManager.GetString("LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map circle color.
        /// </summary>
        public static string MapCircleColor {
            get {
                return ResourceManager.GetString("MapCircleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map color settings.
        /// </summary>
        public static string MapColorSettings {
            get {
                return ResourceManager.GetString("MapColorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map cross hair color.
        /// </summary>
        public static string MapCrossHairColor {
            get {
                return ResourceManager.GetString("MapCrossHairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map surroundings color.
        /// </summary>
        public static string MapSurroundingsColor {
            get {
                return ResourceManager.GetString("MapSurroundingsColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map text color.
        /// </summary>
        public static string MapTextColor {
            get {
                return ResourceManager.GetString("MapTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum axes.
        /// </summary>
        public static string MaximumAxes {
            get {
                return ResourceManager.GetString("MaximumAxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon height °.
        /// </summary>
        public static string MoonDegrees {
            get {
                return ResourceManager.GetString("MoonDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (the Moon).
        /// </summary>
        public static string MoonTime {
            get {
                return ResourceManager.GetString("MoonTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string NAChar {
            get {
                return ResourceManager.GetString("NAChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next day.
        /// </summary>
        public static string NextDay {
            get {
                return ResourceManager.GetString("NextDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object details.
        /// </summary>
        public static string ObjectDetails {
            get {
                return ResourceManager.GetString("ObjectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object diameter.
        /// </summary>
        public static string ObjectDiameter {
            get {
                return ResourceManager.GetString("ObjectDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object name.
        /// </summary>
        public static string ObjectName {
            get {
                return ResourceManager.GetString("ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous day.
        /// </summary>
        public static string PreviousDay {
            get {
                return ResourceManager.GetString("PreviousDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset object graphics.
        /// </summary>
        public static string ResetObjectGraphics {
            get {
                return ResourceManager.GetString("ResetObjectGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right ascension.
        /// </summary>
        public static string RightAscension {
            get {
                return ResourceManager.GetString("RightAscension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right ascension (hours).
        /// </summary>
        public static string RightAscensionHours {
            get {
                return ResourceManager.GetString("RightAscensionHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rise and set graph draw mode.
        /// </summary>
        public static string RiseAndSetGraphDrawMode {
            get {
                return ResourceManager.GetString("RiseAndSetGraphDrawMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to CSV file.
        /// </summary>
        public static string SaveToCSVFile {
            get {
                return ResourceManager.GetString("SaveToCSVFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected object.
        /// </summary>
        public static string SelectedObject {
            get {
                return ResourceManager.GetString("SelectedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected object name.
        /// </summary>
        public static string SelectedObjectName {
            get {
                return ResourceManager.GetString("SelectedObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select location.
        /// </summary>
        public static string SelectLocation {
            get {
                return ResourceManager.GetString("SelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip calculated objects.
        /// </summary>
        public static string SkipCalculatedObjects {
            get {
                return ResourceManager.GetString("SkipCalculatedObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyMap2D - Sky map [Latitude: {0:F5}, Longitude: {1:F5}], [Time: {2}], [Sidereal time: {3}].
        /// </summary>
        public static string SkyMapTitle {
            get {
                return ResourceManager.GetString("SkyMapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify date and time.
        /// </summary>
        public static string SpecifyDateTimeTitle {
            get {
                return ResourceManager.GetString("SpecifyDateTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed per time unit.
        /// </summary>
        public static string SpeedPerTimeUnit {
            get {
                return ResourceManager.GetString("SpeedPerTimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star catalog to use.
        /// </summary>
        public static string StarCatalogSelection {
            get {
                return ResourceManager.GetString("StarCatalogSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star map.
        /// </summary>
        public static string StarMap {
            get {
                return ResourceManager.GetString("StarMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StarMap2D.
        /// </summary>
        public static string StarMap2D {
            get {
                return ResourceManager.GetString("StarMap2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun height °.
        /// </summary>
        public static string SunDegrees {
            get {
                return ResourceManager.GetString("SunDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (the Sun).
        /// </summary>
        public static string SunTime {
            get {
                return ResourceManager.GetString("SunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol circle color.
        /// </summary>
        public static string SymbolCircleColor {
            get {
                return ResourceManager.GetString("SymbolCircleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol color.
        /// </summary>
        public static string SymbolColor {
            get {
                return ResourceManager.GetString("SymbolColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol image.
        /// </summary>
        public static string SymbolImage {
            get {
                return ResourceManager.GetString("SymbolImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test stuff.
        /// </summary>
        public static string TestStuff {
            get {
                return ResourceManager.GetString("TestStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language (localization, a restart is required).
        /// </summary>
        public static string UiLanguageRequireRestart {
            get {
                return ResourceManager.GetString("UiLanguageRequireRestart", resourceCulture);
            }
        }
    }
}
