//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace StarMap2D.Localization {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Units {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Units() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("StarMap2D.Localization.Units", typeof(Units).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aphelion (10⁶ km).
        /// </summary>
        public static string Aphelion_10_6_Km {
            get {
                return ResourceManager.GetString("Aphelion_10_6_Km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string CompassEastShort {
            get {
                return ResourceManager.GetString("CompassEastShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE.
        /// </summary>
        public static string CompassNorthEastShort {
            get {
                return ResourceManager.GetString("CompassNorthEastShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string CompassNorthShort {
            get {
                return ResourceManager.GetString("CompassNorthShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW.
        /// </summary>
        public static string CompassNorthWestShort {
            get {
                return ResourceManager.GetString("CompassNorthWestShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE.
        /// </summary>
        public static string CompassSouthEastShort {
            get {
                return ResourceManager.GetString("CompassSouthEastShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string CompassSouthShort {
            get {
                return ResourceManager.GetString("CompassSouthShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW.
        /// </summary>
        public static string CompassSouthWestShort {
            get {
                return ResourceManager.GetString("CompassSouthWestShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string CompassWestShort {
            get {
                return ResourceManager.GetString("CompassWestShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density (kg/m³).
        /// </summary>
        public static string DensityKgPerM3 {
            get {
                return ResourceManager.GetString("DensityKgPerM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter (km).
        /// </summary>
        public static string DiameterKm {
            get {
                return ResourceManager.GetString("DiameterKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from the Sun (10⁶ km).
        /// </summary>
        public static string DistanceFromSun_10_6_Km {
            get {
                return ResourceManager.GetString("DistanceFromSun_10_6_Km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape velocity (km/s).
        /// </summary>
        public static string EscapeVelocityKmPerS {
            get {
                return ResourceManager.GetString("EscapeVelocityKmPerS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global magnetic field.
        /// </summary>
        public static string GlobalMagneticField {
            get {
                return ResourceManager.GetString("GlobalMagneticField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravity (m/s²).
        /// </summary>
        public static string GravityMPerS2 {
            get {
                return ResourceManager.GetString("GravityMPerS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal, azimuth (degrees).
        /// </summary>
        public static string HorizontalAzimuthDegrees {
            get {
                return ResourceManager.GetString("HorizontalAzimuthDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of day (hours).
        /// </summary>
        public static string LengthOfDayHours {
            get {
                return ResourceManager.GetString("LengthOfDayHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass (10²⁴ kg).
        /// </summary>
        public static string MassKg_10_24 {
            get {
                return ResourceManager.GetString("MassKg_10_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean temperature (°C).
        /// </summary>
        public static string MeanTemperatureDegreesC {
            get {
                return ResourceManager.GetString("MeanTemperatureDegreesC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds.
        /// </summary>
        public static string MilliSeconds {
            get {
                return ResourceManager.GetString("MilliSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minuters.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of moons.
        /// </summary>
        public static string NumberOfMoons {
            get {
                return ResourceManager.GetString("NumberOfMoons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obliquity to orbit (degrees).
        /// </summary>
        public static string ObliquityToOrbitDegrees {
            get {
                return ResourceManager.GetString("ObliquityToOrbitDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orbital eccentricity.
        /// </summary>
        public static string OrbitalEccentricity {
            get {
                return ResourceManager.GetString("OrbitalEccentricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orbital inclination (degrees).
        /// </summary>
        public static string OrbitalInclinationDegrees {
            get {
                return ResourceManager.GetString("OrbitalInclinationDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orbital period (days).
        /// </summary>
        public static string OrbitalPeriodDays {
            get {
                return ResourceManager.GetString("OrbitalPeriodDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orbital velocity (km/s).
        /// </summary>
        public static string OrbitalVelocityKmPerS {
            get {
                return ResourceManager.GetString("OrbitalVelocityKmPerS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perihelion (10⁶ km).
        /// </summary>
        public static string Perihelion_10_6_Km {
            get {
                return ResourceManager.GetString("Perihelion_10_6_Km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring system.
        /// </summary>
        public static string RingSystem {
            get {
                return ResourceManager.GetString("RingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation period (hours).
        /// </summary>
        public static string RotationPeriodHours {
            get {
                return ResourceManager.GetString("RotationPeriodHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface pressure (bars).
        /// </summary>
        public static string SurfacePressureBars {
            get {
                return ResourceManager.GetString("SurfacePressureBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string ValueNo {
            get {
                return ResourceManager.GetString("ValueNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string ValueUnknown {
            get {
                return ResourceManager.GetString("ValueUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string ValueYes {
            get {
                return ResourceManager.GetString("ValueYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        public static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
