//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarMap2D.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarMap2D.Localization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky Map [Latitude: {0:F5}, Longitude: {1:F5}], [Time: {2}]|A title for a window containing a sky map control with latitude and longitude coordinates, date and time..
        /// </summary>
        internal static string msgSkyMap {
            get {
                return ResourceManager.GetString("msgSkyMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d|An abbreviation for days..
        /// </summary>
        internal static string msgTimeIntervalDay {
            get {
                return ResourceManager.GetString("msgTimeIntervalDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h|An abbreviation for hours..
        /// </summary>
        internal static string msgTimeIntervalHour {
            get {
                return ResourceManager.GetString("msgTimeIntervalHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms|An abbreviation for milliseconds..
        /// </summary>
        internal static string msgTimeIntervalMillisecond {
            get {
                return ResourceManager.GetString("msgTimeIntervalMillisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min|An abbreviation for seconds..
        /// </summary>
        internal static string msgTimeIntervalMinute {
            get {
                return ResourceManager.GetString("msgTimeIntervalMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m|An abbreviation for months..
        /// </summary>
        internal static string msgTimeIntervalMonth {
            get {
                return ResourceManager.GetString("msgTimeIntervalMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s|An abbreviation for seconds..
        /// </summary>
        internal static string msgTimeIntervalSecond {
            get {
                return ResourceManager.GetString("msgTimeIntervalSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w|An abbreviation for weeks..
        /// </summary>
        internal static string msgTimeIntervalWeek {
            get {
                return ResourceManager.GetString("msgTimeIntervalWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y|An abbreviation for years..
        /// </summary>
        internal static string msgTimeIntervalYear {
            get {
                return ResourceManager.GetString("msgTimeIntervalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s|An abbreviation for seconds..
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
