//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarMap2D.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarMap2D.Localization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above horizonAbove horizon|A message describing an elliptical object physical property: Above horizon..
        /// </summary>
        internal static string msgAboveHorizon {
            get {
                return ResourceManager.GetString("msgAboveHorizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above horizon: {0}{1}|A text indicating a boolean value if something is above the horizon.
        /// </summary>
        internal static string msgAboveHorizonBooleanValue {
            get {
                return ResourceManager.GetString("msgAboveHorizonBooleanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aphelion (10⁶ km)|A message describing an elliptical object physical property: Aphelion (10⁶ km)..
        /// </summary>
        internal static string msgAphelionKm10_6 {
            get {
                return ResourceManager.GetString("msgAphelionKm10_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time|A message describing a date and time of value calculation..
        /// </summary>
        internal static string msgCalculationDateTime {
            get {
                return ResourceManager.GetString("msgCalculationDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard|A message describing a functionality to copy to clipboard..
        /// </summary>
        internal static string msgCopyToClipboard {
            get {
                return ResourceManager.GetString("msgCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data URL|A message describing an external URL value for additional data..
        /// </summary>
        internal static string msgDataUrl {
            get {
                return ResourceManager.GetString("msgDataUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time: {0}{1}|A text indicating a date and time value.
        /// </summary>
        internal static string msgDateDataDateTimeValue {
            get {
                return ResourceManager.GetString("msgDateDataDateTimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declination (degrees)|A message describing an elliptical object physical property: Declination (degrees)..
        /// </summary>
        internal static string msgDeclination {
            get {
                return ResourceManager.GetString("msgDeclination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declination: {0}{1}|A text indicating a right ascension value.
        /// </summary>
        internal static string msgDeclinationWithValue {
            get {
                return ResourceManager.GetString("msgDeclinationWithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density (kg/m³)|A message describing an elliptical object physical property:  density (kg/m³)..
        /// </summary>
        internal static string msgDensityKgM3 {
            get {
                return ResourceManager.GetString("msgDensityKgM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Date and time|A message describing a date and time of value calculation..
        /// </summary>
        internal static string msgDetailDateTime {
            get {
                return ResourceManager.GetString("msgDetailDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter (km)|A message describing an elliptical object physical property: Diameter (km)..
        /// </summary>
        internal static string msgDiameterKm {
            get {
                return ResourceManager.GetString("msgDiameterKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from sun (10⁶ km)|A message describing an elliptical object physical property: Distance from sun (10⁶ km)..
        /// </summary>
        internal static string msgDistanceFromSunKm10_6 {
            get {
                return ResourceManager.GetString("msgDistanceFromSunKm10_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to east|The compass direction to east..
        /// </summary>
        internal static string msgEast {
            get {
                return ResourceManager.GetString("msgEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to east-north-east|The compass direction to east-north-east..
        /// </summary>
        internal static string msgEastNorthEast {
            get {
                return ResourceManager.GetString("msgEastNorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to east-south-east|The compass direction to east-south-east..
        /// </summary>
        internal static string msgEastSouthEast {
            get {
                return ResourceManager.GetString("msgEastSouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error|A message indicating that a general error occurred..
        /// </summary>
        internal static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The star catalog file &apos;{0}&apos; could not be loaded. Using the default instead.|A message describing to the user that a star catalog with a specified file name could not be loaded and the default is going to be used instead..
        /// </summary>
        internal static string msgErrorLoadingStarCatalog {
            get {
                return ResourceManager.GetString("msgErrorLoadingStarCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape velocity (km/s)|A message describing an elliptical object physical property: Escape velocity (km/s)..
        /// </summary>
        internal static string msgEscapeVelocityKmS {
            get {
                return ResourceManager.GetString("msgEscapeVelocityKmS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the data to the file &apos;{0}&apos; with error message of: &apos;{1}&apos;.|A file saving error occurred with the file name and exception message..
        /// </summary>
        internal static string msgFileSaveFailedError {
            get {
                return ResourceManager.GetString("msgFileSaveFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global magnetic field|A message describing an elliptical object physical property: Global magnetic field..
        /// </summary>
        internal static string msgGlobalMagneticField {
            get {
                return ResourceManager.GetString("msgGlobalMagneticField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravity (m/s²)|A message describing an elliptical object physical property: Gravity (m/s²)..
        /// </summary>
        internal static string msgGravityMS2 {
            get {
                return ResourceManager.GetString("msgGravityMS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal, azimuth (degrees)|A message describing an elliptical object physical property: Horizontal, azimuth (degrees)..
        /// </summary>
        internal static string msgHorizontalDegreesX {
            get {
                return ResourceManager.GetString("msgHorizontalDegreesX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal, altitude (degrees)|A message describing an elliptical object physical property: Horizontal, altitude (degrees)..
        /// </summary>
        internal static string msgHorizontalDegreesY {
            get {
                return ResourceManager.GetString("msgHorizontalDegreesY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal X coordinate degrees: {0}{1}|A text indicating a horizontal X-coordinate value in degrees.
        /// </summary>
        internal static string msgHorizontalXDegreesWithValue {
            get {
                return ResourceManager.GetString("msgHorizontalXDegreesWithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Y coordinate degrees: {0}{1}|A text indicating a horizontal Y-coordinate value in degrees.
        /// </summary>
        internal static string msgHorizontalYDegreesWithValue {
            get {
                return ResourceManager.GetString("msgHorizontalYDegreesWithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude|A message describing latitude..
        /// </summary>
        internal static string msgLatitude {
            get {
                return ResourceManager.GetString("msgLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of day (hours)|A message describing an elliptical object physical property: Length of day (hours)..
        /// </summary>
        internal static string msgLengthOfDayHrs {
            get {
                return ResourceManager.GetString("msgLengthOfDayHrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude|A message describing longitude..
        /// </summary>
        internal static string msgLongitude {
            get {
                return ResourceManager.GetString("msgLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass (10²⁴ kg)|A message describing an elliptical object physical property: Mass (10²⁴ kg)..
        /// </summary>
        internal static string msgMassKg10_24 {
            get {
                return ResourceManager.GetString("msgMassKg10_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean temperature (°C)|A message describing an elliptical object physical property: Mean temperature (°C)..
        /// </summary>
        internal static string msgMeanTemperatureDC {
            get {
                return ResourceManager.GetString("msgMeanTemperatureDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name|A message describing a name value of something..
        /// </summary>
        internal static string msgName {
            get {
                return ResourceManager.GetString("msgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no|A message saying false in form of no..
        /// </summary>
        internal static string msgNo {
            get {
                return ResourceManager.GetString("msgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north|The compass direction to north..
        /// </summary>
        internal static string msgNorth {
            get {
                return ResourceManager.GetString("msgNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north-east|The compass direction to north-east..
        /// </summary>
        internal static string msgNorthEast {
            get {
                return ResourceManager.GetString("msgNorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north-north-east|The compass direction to north-north-east..
        /// </summary>
        internal static string msgNorthNorthEast {
            get {
                return ResourceManager.GetString("msgNorthNorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north-north-west|The compass direction to north-north-west..
        /// </summary>
        internal static string msgNorthNorthWest {
            get {
                return ResourceManager.GetString("msgNorthNorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north-west|The compass direction to north-west..
        /// </summary>
        internal static string msgNorthWest {
            get {
                return ResourceManager.GetString("msgNorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of moons|A message describing an elliptical object physical property: Number of moons..
        /// </summary>
        internal static string msgNumberOfMoons {
            get {
                return ResourceManager.GetString("msgNumberOfMoons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object name: {0}{1}|A message describing a name value of any sky object of any kind..
        /// </summary>
        internal static string msgObjectNameValue {
            get {
                return ResourceManager.GetString("msgObjectNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obliquity to orbit (degrees)|A message describing an elliptical object physical property: Obliquity to orbit (degrees)..
        /// </summary>
        internal static string msgObliquityToOrbitDeg {
            get {
                return ResourceManager.GetString("msgObliquityToOrbitDeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orbital eccentricity|A message describing an elliptical object physical property: Orbital eccentricity..
        /// </summary>
        internal static string msgOrbitalEccentricity {
            get {
                return ResourceManager.GetString("msgOrbitalEccentricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orbital inclination (degrees)|A message describing an elliptical object physical property: Orbital inclination (degrees)..
        /// </summary>
        internal static string msgOrbitalInclinationDeg {
            get {
                return ResourceManager.GetString("msgOrbitalInclinationDeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrbitalPeriod (days)|A message describing an elliptical object physical property: Orbital period (days)..
        /// </summary>
        internal static string msgOrbitalPeriodDays {
            get {
                return ResourceManager.GetString("msgOrbitalPeriodDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrbitalVelocity (km/s)|A message describing an elliptical object physical property: Orbital velocity (km/s)..
        /// </summary>
        internal static string msgOrbitalVelocityKmS {
            get {
                return ResourceManager.GetString("msgOrbitalVelocityKmS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perihelion (10⁶ km)|A message describing an elliptical object physical property: Perihelion (10⁶ km)..
        /// </summary>
        internal static string msgPerihelionKm10_6 {
            get {
                return ResourceManager.GetString("msgPerihelionKm10_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start a process for the file &apos;{0}&apos; with error message of: &apos;{1}&apos;.|A process start error occurred with the file name and exception message..
        /// </summary>
        internal static string msgProcessStartFailed {
            get {
                return ResourceManager.GetString("msgProcessStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right ascension (hours)|A message describing an elliptical object physical property: Right ascension (hours)..
        /// </summary>
        internal static string msgRightAscension {
            get {
                return ResourceManager.GetString("msgRightAscension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right ascension: {0}{1}|A text indicating a right ascension value.
        /// </summary>
        internal static string msgRightAscensionWithValue {
            get {
                return ResourceManager.GetString("msgRightAscensionWithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring systemRing system|A message describing an elliptical object physical property: Ring system..
        /// </summary>
        internal static string msgRingSystem {
            get {
                return ResourceManager.GetString("msgRingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation period (hours)|A message describing an elliptical object physical property: Rotation period (hours)..
        /// </summary>
        internal static string msgRotationPeriodHrs {
            get {
                return ResourceManager.GetString("msgRotationPeriodHrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky Map [Latitude: {0:F5}, Longitude: {1:F5}], [Time: {2}], [Sidereal time: {3}]|A title for a window containing a sky map control with latitude and longitude coordinates, date and time and sidereal time..
        /// </summary>
        internal static string msgSkyMap {
            get {
                return ResourceManager.GetString("msgSkyMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to south|The compass direction to south..
        /// </summary>
        internal static string msgSouth {
            get {
                return ResourceManager.GetString("msgSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to south-east|The compass direction to south-east..
        /// </summary>
        internal static string msgSouthEast {
            get {
                return ResourceManager.GetString("msgSouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to south-south-east|The compass direction to south-south-east..
        /// </summary>
        internal static string msgSouthSouthEast {
            get {
                return ResourceManager.GetString("msgSouthSouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to south-south-west|The compass direction to south-south-west..
        /// </summary>
        internal static string msgSouthSouthWest {
            get {
                return ResourceManager.GetString("msgSouthSouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to south-west|The compass direction to south-west..
        /// </summary>
        internal static string msgSouthWest {
            get {
                return ResourceManager.GetString("msgSouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface pressure (bars)|A message describing an elliptical object physical property: Surface pressure (bars)..
        /// </summary>
        internal static string msgSurfacePressureBars {
            get {
                return ResourceManager.GetString("msgSurfacePressureBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d|An abbreviation for days..
        /// </summary>
        internal static string msgTimeIntervalDay {
            get {
                return ResourceManager.GetString("msgTimeIntervalDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h|An abbreviation for hours..
        /// </summary>
        internal static string msgTimeIntervalHour {
            get {
                return ResourceManager.GetString("msgTimeIntervalHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms|An abbreviation for milliseconds..
        /// </summary>
        internal static string msgTimeIntervalMillisecond {
            get {
                return ResourceManager.GetString("msgTimeIntervalMillisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min|An abbreviation for seconds..
        /// </summary>
        internal static string msgTimeIntervalMinute {
            get {
                return ResourceManager.GetString("msgTimeIntervalMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m|An abbreviation for months..
        /// </summary>
        internal static string msgTimeIntervalMonth {
            get {
                return ResourceManager.GetString("msgTimeIntervalMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s|An abbreviation for seconds..
        /// </summary>
        internal static string msgTimeIntervalSecond {
            get {
                return ResourceManager.GetString("msgTimeIntervalSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w|An abbreviation for weeks..
        /// </summary>
        internal static string msgTimeIntervalWeek {
            get {
                return ResourceManager.GetString("msgTimeIntervalWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y|An abbreviation for years..
        /// </summary>
        internal static string msgTimeIntervalYear {
            get {
                return ResourceManager.GetString("msgTimeIntervalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown|A value describing an unknown value of a physical variable..
        /// </summary>
        internal static string msgUnknownVariableValue {
            get {
                return ResourceManager.GetString("msgUnknownVariableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to west|The compass direction to west..
        /// </summary>
        internal static string msgWest {
            get {
                return ResourceManager.GetString("msgWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to west-north-west|The compass direction to west-north-west..
        /// </summary>
        internal static string msgWestNorthWest {
            get {
                return ResourceManager.GetString("msgWestNorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to west-south-west|The compass direction to west-south-west..
        /// </summary>
        internal static string msgWestSouthWest {
            get {
                return ResourceManager.GetString("msgWestSouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes|A message saying true in form of yes..
        /// </summary>
        internal static string msgYes {
            get {
                return ResourceManager.GetString("msgYes", resourceCulture);
            }
        }
    }
}
