using StarMap2D.Calculations.Constellations.ConstellationClasses;

namespace StarMap2D.Calculations.Constellations.StaticData;

/// <summary>
/// A class to list all constellation class types.
/// </summary>
public class ConstellationTypes
{
    /// <summary>
    /// The types of the constellations.
    /// </summary>
    public static readonly Type[] Types =
    {
        typeof(Andromeda),
        typeof(Antlia),
        typeof(Apus),
        typeof(Aquarius),
        typeof(Aquila),
        typeof(Ara),
        typeof(Aries),
        typeof(Auriga),
        typeof(Boötes),
        typeof(Caelum),
        typeof(Camelopardalis),
        typeof(Cancer),
        typeof(CanesVenatici),
        typeof(CanisMajor),
        typeof(CanisMinor),
        typeof(Capricornus),
        typeof(Carina),
        typeof(Cassiopeia),
        typeof(Centaurus),
        typeof(Cepheus),
        typeof(Cetus),
        typeof(Chamaeleon),
        typeof(Circinus),
        typeof(Columba),
        typeof(ComaBerenices),
        typeof(CoronaAustralis),
        typeof(CoronaBorealis),
        typeof(Corvus),
        typeof(Crater),
        typeof(Crux),
        typeof(Cygnus),
        typeof(Delphinus),
        typeof(Dorado),
        typeof(Draco),
        typeof(Equuleus),
        typeof(Eridanus),
        typeof(Fornax),
        typeof(Gemini),
        typeof(Grus),
        typeof(Hercules),
        typeof(Horologium),
        typeof(Hydra),
        typeof(Hydrus),
        typeof(Indus),
        typeof(Lacerta),
        typeof(Leo),
        typeof(LeoMinor),
        typeof(Lepus),
        typeof(Libra),
        typeof(Lupus),
        typeof(Lynx),
        typeof(Lyra),
        typeof(Mensa),
        typeof(Microscopium),
        typeof(Monoceros),
        typeof(Musca),
        typeof(Norma),
        typeof(Octans),
        typeof(Ophiuchus),
        typeof(Orion),
        typeof(Pavo),
        typeof(Pegasus),
        typeof(Perseus),
        typeof(Phoenix),
        typeof(Pictor),
        typeof(Pisces),
        typeof(PiscisAustrinus),
        typeof(Puppis),
        typeof(Pyxis),
        typeof(Reticulum),
        typeof(Sagitta),
        typeof(Sagittarius),
        typeof(Scorpius),
        typeof(Sculptor),
        typeof(Scutum),
        typeof(SerpensCaput),
        typeof(SerpensCauda),
        typeof(Sextans),
        typeof(Taurus),
        typeof(Telescopium),
        typeof(Triangulum),
        typeof(TriangulumAustrale),
        typeof(Tucana),
        typeof(UrsaMajor),
        typeof(UrsaMinor),
        typeof(Vela),
        typeof(Virgo),
        typeof(Volans),
        typeof(Vulpecula),
    };
}